#!/usr/bin/perl -w
 
$filename = $ARGV[0];
 
if (length($filename)) {
    open(FILE, $filename) or die "Couldn't read $filename: $!";
 
    while (my $string = <FILE>) {
        chomp;
 
        if ($string =~ /\.vnic\.oc/ ) {
            my @listvmbmResponse = split(' ', $string);
        if ($listvmbmResponse[6] ne ""  )
                { print "vnic\n{\"vnicId\":\"$listvmbmResponse[6]\",\"resourceId\":\"$listvmbmResponse[3]\",\"resourceType\":\"database\"}\n"; }
        if ($listvmbmResponse[8] ne ""  )
                { print "vnic\n{\"vnicId\":\"$listvmbmResponse[8]\",\"resourceId\":\"$listvmbmResponse[3]\",\"resourceType\":\"database\"}\n"; }
        }
        else {
            next;
        }
    }
}
else {
    print "Please enter a valid filename\n";
} 
